//CONTADOR
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const INCREMENT_5 = 'INCREMENT_5';
export const DECREMENT_5 = 'DECREMENT_5';
export const RESET = 'RESET';

//SHOPPING CART
export const ADD_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_ONE_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const REMOVE_ALL_FROM_CART = 'REMOVE_ALL_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';